### ISSUE TITLE
Supplied values.yaml conflicts with latest stable/prometheus

### ISSUE THREAD

**Issue by mramshaw** [karthequian/prometheus-demo#1]
The server component fails to start - however it looks as if all of the config is included with the stock stable/prometheus (Status -> Configuration) and is therefore not needed.

So I've removed the prometheus.yml part from the values.yaml file.

Also, it looks like "node_cpu" was renamed to "machine_cpu_cores".

**Comment by karthequian** [comment]
Thanks @mramshaw!

**Comment by mramshaw** [comment]
No problems!
